name: CI
on: 
  pull_request:
    types: [opened, edited, synchronize, labeled, unlabeled, ready_for_review, reopened]
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.8.2"
      - name: Sync dependencies
        run: |
          uv sync --all-groups
      - name: Static code check
        run: uv run poe ci_checker
      - name: Check docs build
        working-directory: ./docs
        run: |
          make html
      - name: Check PR title style
        uses: actions/github-script@v7
        with:
          script: |
              const title = context.payload.pull_request.title;
              const labels = context.payload.pull_request.labels.map(l => l.name);
              if (labels.includes('dev')) {
                const regex = /^(?!feat|fix|refactor|docs|perf|style|test|chore|revert)[a-z].*$/;
                if (!regex.test(title)) {
                  core.setFailed(
                    `PR title "${title}" does not match the commit format for non-user-facing changes`
                  );
                }
              } else {
                const regex = /^(feat|fix|refactor|docs|perf|style|test|chore|revert)!?:[ ][a-z].*$/;
                if (!regex.test(title)) {
                  core.setFailed(
                    `PR title "${title}" does not match the expected conventional commit format for user-facing changes`
                  );
                }
              }
